"""Add Order model

Revision ID: b9ed223ca138
Revises: 
Create Date: 2023-07-20 23:00:44.081200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ed223ca138'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base', sa.String(), nullable=True),
    sa.Column('toppings', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('temp', sa.String(), nullable=True),
    sa.Column('sweetness', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
